version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27017/used_market
      - NEXTAUTH_URL=http://localhost:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
